### PR TITLE
Use commands from Declare Commands packet for tab-completion on 1.12

### LINKED ISSUE #328: shows unavailable commands in tab-complete
**Describe the bug, provide any errors**
my server is 1.16.5 paperspigot, ViaVersion-3.2.1, ViaBackwards-3.2.0

if I enter a command on client version 1.16.5, everything works as tab-complete should, the commands are only offered to which the player has rights.  
but if you go to the server on client version 1.12.2, then it will offer all server commands, including those for which the player has no rights

**How can we reproduce it?**
1. Login on 1.12.2
2. write `/` and press TAB
3.  you will see commands that you do not have permission to.

**Expected behaviour**
I expect not to display commands in the tab-complete output that the player does not have permission to.

**Screenshots**
image

**ViaVersion Dump:**
https://dump.viaversion.com/8b60192fff5e03d58fe09519496532ead17c68184892d9bf18c8b70229a2a29f

**Additional server info**
none, only Via  
no bungeecord

**Checklist**
- [x] I have included a ViaVersion dump
- [ ] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

### PR DESCRIPTION
**Pull request by MrMicky-FR**
This hides unavailable commands in tab-complete (fix #328)

It reproduces the same behavior as Minecraft 1.13+ clients (use commands from Declare Commands packet to tab-complete commands names and send tab-complete packet to the server for commands arguments)

### CODE REVIEW

File: common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java [hunk 1]
```diff
@@ -342,34 +385,49 @@ public void handle(PacketWrapper wrapper) throws Exception {
...
+                            if (startsWithIgnoreCase(value, command)) {
+                                suggestions.add(value);
                             }
-                            response.send(protocol.getClass());
                         }
                     }
 
+                    if (!suggestions.isEmpty()) {
+                        wrapper.cancel();
+                        PacketWrapper response = wrapper.create(0xE);
```
Comment (KennyTV) [inline common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java:413]: Use a `ClientboundPackets1_13` enum entry here

**Review by KennyTV — APPROVED** [review]
Looks good, thank you! Just some minor things to change

File: common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java [hunk 2]
```diff
@@ -342,34 +386,49 @@ public void handle(PacketWrapper wrapper) throws Exception {
...
+                            if (startsWithIgnoreCase(value, command)) {
+                                suggestions.add(value);
                             }
-                            response.send(protocol.getClass());
                         }
                     }
 
+                    if (!suggestions.isEmpty()) {
+                        wrapper.cancel();
+                        PacketWrapper response = wrapper.create(ClientboundPackets1_13.TAB_COMPLETE);
```
Comment (KennyTV) [inline common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_12_2to1_13/packets/PlayerPacket1_13.java:414]: Whoops sorry, this should be from the ClientboundPackets1_12_1 enum

**Review by KennyTV — CHANGES_REQUESTED** [review]

**Review by KennyTV — APPROVED** [review]
Thank you!
