### PR TITLE
Fix colored inventory titles on 1.13 and below

### LINKED ISSUE #269: 1.16.3 colored inventory titles
**Describe the bug, provide any errors**
Colored inventory titles aren't colored in older versions than the server version. They are grey and not in the color they should be. The server version is 1.16.3, with the server version 1.15.2 it worked correctly

**How can we reproduce it?**
1. Login on 1.12.2 (or 1.8.9, ...)
2. Open an colored inventory (e.g. with the name "§cTest")
3. The displayed inventory isn't in the color it should be

**Expected behaviour**
That the inventory title is in the correct color

**ViaVersion Dump:**
- https://dump.viaversion.com/c6ec8c70664d1a9c699d4aa155c222dee78c0700f1313118c559266b70b5c0fd

**Additional server info**
BungeeCord

**Checklist**
- [x] I have included a ViaVersion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

### PR DESCRIPTION
**Pull request by MrMicky-FR**
Fixes colored inventory titles on 1.13 and below, by converting JSON formatting to legacy formatting because theses versions supports colors only with legacy formatting: https://bugs.mojang.com/browse/MC-124543

Fixes #269

### CODE REVIEW

File: common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_13to1_13_1/Protocol1_13To1_13_1.java [hunk 1]
```diff
@@ -96,6 +100,25 @@ public void handle(PacketWrapper wrapper) throws Exception {
...
+                map(Type.UNSIGNED_BYTE); // Id
+                map(Type.STRING); // Window Type
+                handler(wrapper -> {
+                    JsonElement title = wrapper.read(Type.COMPONENT);
+                    translatableRewriter.processText(title);
+
+                    // https://bugs.mojang.com/browse/MC-124543
+                    Component component = GsonComponentSerializer.gson().deserialize(title.toString());
+                    JsonObject legacyComponent = new JsonObject();
+                    legacyComponent.addProperty("text", LegacyComponentSerializer.legacySection().serialize(component));
```
Comment (KennyTV) [inline common/src/main/java/nl/matsv/viabackwards/protocol/protocol1_13to1_13_1/Protocol1_13To1_13_1.java:115]: Use `ChatRewriter.jsonToLegacyText(title.toString())` to add it to the legacyComponent here

**Review by KennyTV — APPROVED** [review]
Just one minor change, looks good otherwise. I'll merge after that 👍

**Comment by KennyTV** [comment]
Thank you!
