### PR TITLE
Delay mannequin spawning for proper skin application

### LINKED ISSUE #1143: Mannequin skins not visible on 1.21.8 and older clients
### '/viaversion dump' Output

https://dump.viaversion.com/fd3d37580f8209a703d3b83a5d3bce7da7ec453b04c12ed369ad0c893456b639

### Server/Client Error

_No response_

### Bug Description

Mannequins with a custom skin (using profile) display correctly on 1.21.10 clients, but older clients such as 1.21.8 and below show them without skin.

### Steps to Reproduce

1. Start a 1.21.10 server with ViaVersion and ViaBackwards 
2. Join with a 1.21.8 or older client.
3. Place a mannequin with a skin: `/summon mannequin ~ ~ ~ {profile:"pukkles"}`

### Additional Server Info

This issue occurred on PurpurMC 1.21.10. I tested with only ViaVersion and ViaBackwards and the issue persisted. I am not using a proxy.

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [x] I have included a ViaVersion dump.
- [x] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

### PR DESCRIPTION
**Pull request by Owen1212055**
Fixes #1143

This uses an approach similar to what was done with boats where we pretty much track everything about the entity and then spawn it when the entity meta is recieved.

This must be done because the skin data must be sent on the first player info received, which MUST happen after the entity meta is sent in order to grab that info. So, we have to delay spawning the entity.

This also adds tracking for the entity equipment.

I also make sure that this properly supports resending when the skin is changed. This also properly tracks with the name change.

### CODE REVIEW

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 1]
```diff
@@ -87,13 +94,131 @@ public void registerPackets() {
...
+
+                final float pitch = wrapper.get(Types.BYTE, 0) * 256.0F / 360.0F;
+                final float yaw = wrapper.get(Types.BYTE, 1) * 256.0F / 360.0F;
+
                 final String name = randomHackyEmptyName();
                 final MannequinData mannequinData = new MannequinData(uuid, name);
-                tracker(wrapper.user()).entity(entityId).data().put(mannequinData);
-                sendInitialPlayerInfoUpdate(wrapper, mannequinData);
+                final TrackedEntity trackedEntity = tracker(wrapper.user()).entity(entityId);
+                if (trackedEntity == null) {
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: The null check isn't needed

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 2]
```diff
@@ -87,13 +94,131 @@ public void registerPackets() {
...
+            final int entityId = wrapper.passthrough(Types.VAR_INT); // Entity ID
+
+            final double x = wrapper.passthrough(Types.DOUBLE); // X
+            final double y = wrapper.passthrough(Types.DOUBLE); // Y
+            final double z = wrapper.passthrough(Types.DOUBLE); // Z
+
+            // Unused...
+            wrapper.write(Types.DOUBLE, 0D); // Delta movement X
+            wrapper.write(Types.DOUBLE, 0D); // Delta movement Y
+            wrapper.write(Types.DOUBLE, 0D); // Delta movement Z
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: This definitely shouldn't be be here

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 3]
```diff
@@ -87,13 +94,131 @@ public void registerPackets() {
...
+            wrapper.passthrough(Types.DOUBLE); // Delta movement X
+            wrapper.passthrough(Types.DOUBLE); // Delta movement Y
+            wrapper.passthrough(Types.DOUBLE); // Delta movement Z
+
+            final float yaw = wrapper.passthrough(Types.FLOAT);
+            final float pitch = wrapper.passthrough(Types.FLOAT);
+
+            final EntityTracker1_21_9 tracker = tracker(wrapper.user());
+            final TrackedEntity trackedEntity = tracker.entity(entityId);
+            if (trackedEntity == null) {
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]:
```suggestion
            if (trackedEntity == null || !trackedEntity.hasData()) {
```

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 4]
```diff
@@ -87,13 +94,131 @@ public void registerPackets() {
...
+        protocol.registerClientbound(ClientboundPackets1_21_9.MOVE_ENTITY_ROT, wrapper -> storeMovementMannequinData(wrapper, false, true));
+
+        // Track passengers
+        protocol.registerClientbound(ClientboundPackets1_21_9.SET_PASSENGERS, wrapper -> {
+            final int vehicleId = wrapper.passthrough(Types.VAR_INT);
+            final int[] passengerIds = wrapper.passthrough(Types.VAR_INT_ARRAY_PRIMITIVE);
+
+            final EntityTracker1_21_9 tracker = tracker(wrapper.user());
+            final TrackedEntity trackedEntity = tracker.entity(vehicleId);
+            if (trackedEntity != null) {
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: also hasData here

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 5]
```diff
@@ -135,8 +260,34 @@ public void registerPackets() {
...
     }
 
-    private void sendInitialPlayerInfoUpdate(final PacketWrapper wrapper, final MannequinData mannequinData) {
-        final PacketWrapper playerInfo = wrapper.create(ClientboundPackets1_21_6.PLAYER_INFO_UPDATE);
+    private void storeMovementMannequinData(final PacketWrapper wrapper, final boolean position, final boolean rotation) {
+        final int entityId = wrapper.passthrough(Types.VAR_INT); // Entity id
+
+        final EntityTracker1_21_9 tracker = tracker(wrapper.user());
+        final TrackedEntity trackedEntity = tracker(wrapper.user()).entity(entityId);
+        if (trackedEntity == null) {
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: hasData

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java [hunk 6]
```diff
@@ -283,15 +441,78 @@ protected void registerRewrites() {
...
+                // Re-attach all passengers
+                if (entity.passengers() != null) {
+                    final PacketWrapper setPassengersPacket = PacketWrapper.create(ClientboundPackets1_21_6.SET_PASSENGERS, event.user());
+                    setPassengersPacket.write(Types.VAR_INT, event.entityId());
+                    setPassengersPacket.write(Types.VAR_INT_ARRAY_PRIMITIVE, entity.passengers());
+                    setPassengersPacket.send(Protocol1_21_9To1_21_7.class);
+                }
+
+                // Put on items
+                if (!entity.getItemMap().isEmpty()) {
```
[the remark this answers is not in the document]
Comment (Owen1212055) [reply common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: I wasnt sure if it was hugely important, up to you it can be done.

**Comment by Owen1212055** [comment]
One issue I am not really sure about what is going on is that if you join a server with these manniquins it seems the head rotation is wrong.

However, the head rotation is correct when live respawning it, simply not when initially joining the server. So, would love some pointers if possible.

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (FlorianMichael) [reply common/src/main/java/com/viaversion/viabackwards/protocol/v1_21_9to1_21_7/rewriter/EntityPacketRewriter1_21_9.java]: yeah at least I did it in the boat code. I don't remember anymore whether it was needed but it surely won't hurt to also have it here.

**Comment by Owen1212055** [comment]
@FlorianMichael Otherwise do you have any comment with the head rotation issue? I'm not too familiar with head rotation with player entities as I vaguely remember there being some syncing issues.

**Comment by florianreuth** [comment]
Currently doing something else but I already had planned to look at it later :)

**Comment by florianreuth** [comment]
Found something else: Your emulation code is assuming that the skin entity data is always send which isn't the case (e.g if the mannequin doesn't have a skin) so right now the mannequin doesn't spawn at all if no skin is set (which is the Vanilla default case with a simple /summon). ~~Currently thinking about how this can be properly handled:~~

~~In theory, we would need to always immediately spawn the mannequin and later replace the entity when the skin data is sent. Problem with that is entity id conflicting / it would require even more uglier tracking and hacks.....
Maybe it's easier to just either wait a few seconds for the skin data and then fallback spawn the mannequin or just have the skin support as optional config option?~~ Still had the pre 1.16 behavior in mind, sorry about that

**Comment by florianreuth** [comment]
image
Not sure if I'm doing something wrong, but I don't get a skin:

`/summon mannequin ~ ~ ~ {profile:{"name":"EnZaXD","id":[954437565,-1071166292,-1908981416,1896491133],"properties":[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTc2NjYxNDE0MzA5MSwKICAicHJvZmlsZUlkIiA6ICIzOGUzOGZiZGMwMjc0Y2FjOGUzNzQxNTg3MTBhMjg3ZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFblphWEQiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQ4M2U2MjEzMjBjMWZhMmFhMzIyNjZkMTBiMDRjNzdlZDQxYjY4MDYxZTQ4NTc5MjM5YzZhYjdhODU5Njg2NiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZjZlNGYxNDgwMWYzZWE1NWUzZDk1YjliNGVmM2I1ZTg4MDJkOTQ3ZjY2OWRlOTNkNmVjNGI5MzU0YTQzNmIiCiAgICB9CiAgfQp9"}]}}`

**Comment by Owen1212055** [comment]
> image Not sure if I'm doing something wrong, but I don't get a skin:
> `/summon mannequin ~ ~ ~ {profile:{"name":"EnZaXD","id":[954437565,-1071166292,-1908981416,1896491133],"properties":[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTc2NjYxNDE0MzA5MSwKICAicHJvZmlsZUlkIiA6ICIzOGUzOGZiZGMwMjc0Y2FjOGUzNzQxNTg3MTBhMjg3ZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFblphWEQiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQ4M2U2MjEzMjBjMWZhMmFhMzIyNjZkMTBiMDRjNzdlZDQxYjY4MDYxZTQ4NTc5MjM5YzZhYjdhODU5Njg2NiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZjZlNGYxNDgwMWYzZWE1NWUzZDk1YjliNGVmM2I1ZTg4MDJkOTQ3ZjY2OWRlOTNkNmVjNGI5MzU0YTQzNmIiCiAgICB9CiAgfQp9"}]}}`

You need a signature. The client cannot display skins that dont have signatures  cause of player entities funnyness.

**Comment by Owen1212055** [comment]
> Found something else: Your emulation code is assuming that the skin entity data is always send which isn't the case (e.g if the mannequin doesn't have a skin) so right now the mannequin doesn't spawn at all if no skin is set (which is the Vanilla default case with a simple /summon). ~Currently thinking about how this can be properly handled:~

That is a good point... hm... I am not quite sure however what the best way to solve this is? Do you have any opinions?

**Comment by florianreuth** [comment]
Yeah I already had a fix in my mind locally, will try it out and push to here if it works. Also head rotations seem fine to me, but I noticed that the remapping of ROTATE_HEAD is wrong.

**Comment by florianreuth** [comment]
> > image Not sure if I'm doing something wrong, but I don't get a skin:
> > `/summon mannequin ~ ~ ~ {profile:{"name":"EnZaXD","id":[954437565,-1071166292,-1908981416,1896491133],"properties":[{"name":"textures","value":"ewogICJ0aW1lc3RhbXAiIDogMTc2NjYxNDE0MzA5MSwKICAicHJvZmlsZUlkIiA6ICIzOGUzOGZiZGMwMjc0Y2FjOGUzNzQxNTg3MTBhMjg3ZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFblphWEQiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQ4M2U2MjEzMjBjMWZhMmFhMzIyNjZkMTBiMDRjNzdlZDQxYjY4MDYxZTQ4NTc5MjM5YzZhYjdhODU5Njg2NiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2EzZjZlNGYxNDgwMWYzZWE1NWUzZDk1YjliNGVmM2I1ZTg4MDJkOTQ3ZjY2OWRlOTNkNmVjNGI5MzU0YTQzNmIiCiAgICB9CiAgfQp9"}]}}`
> 
> You need a signature. The client cannot display skins that dont have signatures cause of player entities funnyness.

Hmm they shouldn't be needed though. It works like this in Vanilla, even without the properties/id part. But yeah I guess that's too hard to fix. Pushed a fix to the other issue now.

**Comment by florianreuth** [comment]
head rotations should also be fixed now :)

**Comment by Owen1212055** [comment]
Thank you! I will just test and double check.

**Comment by Owen1212055** [comment]
After testing, seems good!

**Comment by kennytv** [comment]
What you used when going from byte to float was the wrong way around, that's where the issues came from (all yaw pitch and headyaw)
