### PR TITLE
Prevent 1.16 -> 1.17 cursor desync with dragging (mostly fixes #389)

### LINKED ISSUE #389: Inventory desync issues
### '/viaversion dump' Output

https://dump.viaversion.com/2292498dbe3a81ee107fbab916325e9fabc4c32ea5a4a83a225489db115cf432

### Console Error

```
None
```

### Bug Description

When moving items in inventory's it duplicates sometimes (ghost items). And it's quite annoying if i need to provide anything more to fix this say so.

### Steps to Reproduce

Login with a client lower than 1.17 (as stated in the readme)
move items in ur inventory 
and it will sometimes duplicate.

### Expected Behavior

No ghost items.

### Additional Server Info

https://www.youtube.com/watch?v=t9EdKSdPJgc
https://streamable.com/i6ijtd

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

### PR DESCRIPTION
**Pull request by Quantum64**
1.17 clients must report modified slots and the carried item when clicking a window, and the server will respond by sending set slot packets where it disagrees with the client about the window state. It's fine to send an empty modified items array for legacy clients, although we miss out on the error checking benefit, however, failing to send the correct carried item is problematic.

When a legacy client sends the start drag packet with an incorrect carried item (and since the current behavior is to send the clicked item as the carried item and typically drag actions occur on empty slots, this is almost always the case), the server will detect the desynchronization of the carried item and immediately resend the correct carried item before the drag action has occurred. Due to some completely bizarre behavior of legacy clients, the client receives the correct amount right after it starts dragging but does not apply it to the item stack being dragged until *after* the drag action completes. This is problematic because the drag action itself affects the count of the carried item, so resetting it to the pre-drag count causes ghost carried items.

My solution is to send an educated guess about what the actual carried item probably is, rather than the clicked slot, when the start drag packet is sent. Hopefully, the server accepts this guess and does not attempt to resend the carried item, which is what causes the issue. The guess is made by saving the last left-clicked stack, the last right-clicked stack if the previous cursor was not empty, or half of the last right-clicked stack if the previous cursor was empty. This only partially replicates vanilla behavior, but it's good enough to mitigate this issue in most cases. Additionally, we listen for each time the server tells us the actual state of the carried item and update our guess accordingly. This second method uses takes advantage fact that Via sends incorrect state IDs for each set slot action during an ongoing drag, as well as the stop drag packet. Via will only send any given state ID for a single click packet, but the vanilla client will send the same state ID for each packet in the drag action series. The server is unhappy about this and resends the entire window contents for each modified slot in a drag action and one additional time for the completed drag. If this bug is ever fixed, it will cause my patch here to stop working correctly, since, without the extra information about the carried item gained from these window resends, we would not be able to determine the amount of an item left immediately after a drag action. Since one drag action can immediately follow another, the carried count must be appropriately updated after each drag. While helpful here, this issue has the unfortunate side effect of consuming quite a bit of unnecessary bandwidth.

This is an extremely janky fix that does not cover all edge cases. Specifically, the logic that detects the current carried item is limited and incomplete. Although the results are passable right now, I fear that eventually, as the server becomes more strict or finds additional uses for the reported carried and modified items, simple fixes like these will not be enough. Ultimately, Via may need to store a replica of every container state and update it appropriately when either the client or server makes modifications. That would enable us to use the actual container state to fill in the gaps left by legacy clients. This would be a future-proof solution, however, the implementation effort is high and would involve replicating all of the vanilla inventory click logic.

### CODE REVIEW

**Review by RaphiMC — CHANGES_REQUESTED** [review]
This pull request looks promising, but there are some errors in the code which would break things over time or when Via has more protocols after those ones you changed. It's related to how items are tracked. You should not use the Item.copy() method as that doesn't copy the tag of the item, but instead only uses the same reference. This causes the tracked tag to be wrong, after the item goes through further remapping later on (for example: The item which you track in set slot, might have its tag rewritten in the next protocol in the pipeline for which the same reference gets used). Also the item should be fully copied (actually copy the tag) before sending it into the Via pipeline, as any remapping which occurs there would also affect the tracked item.
To copy an item fully you should invoke the constructor like this:
`Item copied = new Item(toCopy.identifier(), toCopy.amount(), toCopy.data(), toCopy.tag() == null ? null : toCopy.tag().clone());`
I don't know if its an oversight in Via, that the copy method of Item is not actually copying the tag, but it tricked me a couple of times as well regarding item tracking.

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java [hunk 1]
```diff
@@ -82,24 +83,85 @@ public void registerMap() {
...
+                    if (mode == 0 && button == 0 && clicked != null) {
+                        // Left click PICKUP
+                        // Carried item will (usually) be the entire clicked stack
+                        state.setLastCursorItem(clicked.copy());
+                    } else if (mode == 0 && button == 1 && clicked != null) {
+                        // Right click PICKUP
+                        // Carried item will (usually) be half of the clicked stack (rounding up)
+                        // if the clicked slot is empty, otherwise it will (usually) be the whole clicked stack
+                        state.setLastCursorItem(clicked.copy());
+                        if (state.getLastCursorItem() == null) {
```
Comment (RaphiMC) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:117]: This can never be true, as you check if clicked != null a couple of lines above

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java [hunk 2]
```diff
@@ -82,24 +83,85 @@ public void registerMap() {
...
+                    Item carried = wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    if (carried != null && windowId == -1 && slot == -1) {
+                        // This is related to the hack to fix click and drag ghost items above.
+                        // After a completed drag, we have no idea how many items remain on the cursor,
+                        // and vanilla logic replication would be required to calculate the value.
+                        // When the click drag complete packet is sent, we will send an incorrect
+                        // carried item, and the server will helpfully send this packet allowing us
+                        // to update the internal state. This is necessary for fixing multiple sequential
+                        // click drag actions without intermittent pickup actions.
+                        wrapper.user().get(PlayerLastCursorItem.class).setLastCursorItem(handleItemToServer(carried.copy()));
```
Comment (RaphiMC) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:158]: You probably should not call handleItemToServer() here, as that method remaps items in client -> server direction, which set slot is not. You should instead be storing the item which is returned from handleItemToClient() a couple of lines below. This ensures your tracker has the 1.16.4 item tracked.

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java [hunk 3]
```diff
@@ -147,6 +148,8 @@ public void registerMap() {
                     short slot = wrapper.passthrough(Type.SHORT);
 
                     Item carried = wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    wrapper.write(Type.FLAT_VAR_INT_ITEM, handleItemToClient(carried));
```
Comment (RaphiMC) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:151]: I changed my comment before. You should be tracking (copied) the item before remapping it to 1.16.4

Comment (Quantum64) [reply common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:151]: Makes sense, since we aren't mapping it back to the server item after it's saved

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java [hunk 4]
```diff
@@ -82,24 +83,85 @@ public void registerMap() {
...
+                        // Preserve guessed carried item and forward to server
+                        // This mostly fixes the click and drag ghost item issue
+
+                        // no-op
+                    } else {
+                        // Carried item unknown (TODO)
+                        state.setLastCursorItem(null);
+                    }
+
+                    Item carried = state.getLastCursorItem();
```
Comment (RaphiMC) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:132]: You should be returning a full copy of the item or copy it here, as writing it into the PacketWrapper will cause that item instance to be modified by later protocols which would cause the item in the tracker to be modified to a much newer version.

Comment (Quantum64) [reply common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:132]: Mutability is terrifying

Comment (RaphiMC) [reply common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_16_4to1_17/packets/BlockItemPackets1_17.java:132]: It is, but its way more performant using the same item instance than copying it everytime it enters another protocol. Only copying where neccessary is better. Tbh. it would not be that bad if the copy method of Item would actually do what it should.

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_17to1_17_1/Protocol1_17To1_17_1.java [hunk 5]
```diff
@@ -91,7 +92,14 @@ public void registerMap() {
...
 
                     // Carried item - should work without adding it to the array above
-                    wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    Item carried = wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    if (carried != null) {
+                        // For click drag ghost item fix -- since the state ID is always wrong,
+                        // the server always resends the entire window contents after a drag action,
+                        // which is useful since we need to update the carried item in preparation
+                        // for a subsequent drag
+                        wrapper.user().get(PlayerLastCursorItem.class).setLastCursorItem(carried.copy());
```
Comment (RaphiMC) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_17to1_17_1/Protocol1_17To1_17_1.java:101]: This copy call can now be removed

**Review by RaphiMC — APPROVED** [review]
Code now looks good to me. I did not check if the window click logic is correct/working.

**Comment by kennytv** [comment]
Not sure if this is fixable with the current way of things, but when dragging with left click it sometimes treats it like a double click on an item to collect everything. To reproduce, just hold leftclick and keep the mouse moving while releasing it, should consistently happen after the first or second try https://streamable.com/347v07

File: common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_17to1_17_1/Protocol1_17To1_17_1.java [hunk 6]
```diff
@@ -91,7 +92,14 @@ public void registerMap() {
...
 
                     // Carried item - should work without adding it to the array above
-                    wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    Item carried = wrapper.read(Type.FLAT_VAR_INT_ITEM);
+                    if (carried != null) {
+                        // For click drag ghost item fix -- since the state ID is always wrong,
+                        // the server always resends the entire window contents after a drag action,
+                        // which is useful since we need to update the carried item in preparation
+                        // for a subsequent drag
+                        wrapper.user().get(PlayerLastCursorItem.class).setLastCursorItem(carried);
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/protocol1_17to1_17_1/Protocol1_17To1_17_1.java:101]: You have to check if the PlayerLastCursorItem object is null (when the player is a 1.17.0 client). And shouldn't this also set the last cursor item if it is null?

**Review by kennytv — CHANGES_REQUESTED** [review]

**Comment by Quantum64** [comment]
> Not sure if this is fixable with the current way of things, but when dragging with left click it sometimes treats it like a double click on an item to collect everything. To reproduce, just hold leftclick and keep the mouse moving while releasing it, should consistently happen after the first or second try https://streamable.com/347v07

What version is this? This does not reproduce for me on 1.8.8.

**Comment by kennytv** [comment]
1.16.5 on a 1.18.2 server

**Comment by Quantum64** [comment]
Ok, it looks like 1.8 has some sort of cooldown for when you can start another drag after finishing one that 1.16 does not have. I'll take a look.

**Comment by Quantum64** [comment]
> 1.16.5 on a 1.18.2 server

Not able to reproduce on a 1.18.2 paper server with via running on a new velocity 3 snapshot. Maybe it only happens when running via on the server directly? I won't be able to try that for a bit.

https://user-images.githubusercontent.com/3969183/158554129-3b2f1804-d24d-4201-8fe0-18ba541f2994.mp4

**Comment by kennytv** [comment]
Huh, I'd try doing the same movement as I did in that first part; move it one to the right and release, then do that again only one to the right; both keeping the mouse still moving when you release it. It being on the proxy shouldn't make that any different

**Review by kennytv — APPROVED** [review]
Thank you!
