### PR TITLE
Fix bed sleep client crash

### LINKED ISSUE #447: Crash when joining a 1.20-1.20.1 server using 1.7.2 (viaproxy)
### `/viaversion dump` Output

not possible

### Console Error

i'm going to put the client log here since there's no error in console
https://paste.gg/p/anonymous/f503318f20fa4957a377a7e25e851cd0

### Bug Description

my client crashed out of no where and kept doing it when logging back in

### Steps to Reproduce

I don't know...

### Expected Behavior

Not to crash the client

### Additional Server Info

this was taken from the info on there discord:
IP: snapshot.8bit.ca
Version: 1.20.1
DOES THE SERVER HAVE PLUGINS/MODS?

snapshot.8bit.ca runs either on a vanilla or fabric server. 

Due to the nature of snapshot servers, plugin/mod support is very limited, however we have a custom re-creation of the Moon Dimension from 23w13a_or_b, preserving its history on the server and continuing its legacy into the future.

The server is currently running these mods:
Fabric API;
No Chat Reports;
Styled Player List;
Starlight;
Lithium.
(& two privately commissioned mods) 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

### LINKED ISSUE #483: Cant join with 1.7 on 1.20 server
### `/viaversion dump` Output

https://dump.viaversion.com/38dd9fe17230dd7fa32d463ee1279569f721f7e3ae25050acbd340c9a5ec40c6

### Console Error

Client Error, No console error

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/30/24 1:37 PM
Description: Unexpected error

java.lang.ClassCastException: yv cannot be cast to yz
	at hp.a(SourceFile:51)
	at bjb.a(SourceFile:499)
	at hp.a(SourceFile:47)
	at hp.a(SourceFile:12)
	at ej.a(SourceFile:174)
	at bje.e(SourceFile:212)
	at bao.p(SourceFile:1306)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at hp.a(SourceFile:51)
	at bjb.a(SourceFile:499)
	at hp.a(SourceFile:47)
	at hp.a(SourceFile:12)
	at ej.a(SourceFile:174)
	at bje.e(SourceFile:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['LinsaFTW'/28, l='MpServer', x=1094.63, y=-58.38, z=-1533.46]]
	Chunk stats: MultiplayerChunkCache: 12, 12
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1101,-61,-1543), Chunk: (at 13,-4,9 in 68,-97; contains blocks 1088,0,-1552 to 1103,255,-1537), Region: (2,-4; contains chunks 64,-128 to 95,-97, blocks 1024,0,-2048 to 1535,255,-1537)
	Level time: 1198599 game time, 1198599 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 5 total; [yv['Villager'/17, l='MpServer', x=1104.50, y=-58.44, z=-1551.50], wo['Pig'/6, l='MpServer', x=1060.75, y=-60.00, z=-1522.72], wi['Donkey'/10, l='MpServer', x=1074.41, y=-60.08, z=-1505.34], bjk['LinsaFTW'/28, l='MpServer', x=1094.63, y=-58.38, z=-1533.46], wp['�ex2'/15, l='MpServer', x=1099.50, y=-60.08, z=-1511.72]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bjf.a(SourceFile:289)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:742)
	at net.minecraft.client.main.Main.main(SourceFile:148)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 95963368 bytes (91 MB) / 419430400 bytes (400 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:+DisableExplicitGC -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.17, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

### Bug Description

Cant join with 1.7

### Steps to Reproduce

Login with a 1.7 client

### Expected Behavior

Being able to login with no errors

### Additional Server Info

I use FlameCord, the plugins are installed in spigot 1.20. Issue is not happening on 1.8. I sometimes get an empty world. 
image

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

### LINKED ISSUE #532: Game crashes while playing on 1.7.2 on a 1.21 server (only on 1.7.X)
### `/viaversion dump` Output

https://dump.viaversion.com/3bc799d84ee6e98a52bc4b426fb9813630910de4818be03906c8a6ee2b11d8a3

### Client Crash Log

[1.7.2 client crash log](https://mclo.gs/PXZGGFu)

### Bug Description

Sometimes it works just fine, but when I go into a certain area, 1.7.2 immediately crashes. I also had an issue like this before, and it seemed like there was an entity with invalid data or something, so maybe the same issue is occurring here?

### Steps to Reproduce

1. Join hoobs.live on 1.7.2 using ViaProxy.
2. Go forward towards the farm.
3. The client will crash with a crash log (or it'll crash immediately when you join).

### Expected Behavior

this is kind of a no brainer lol. no crash.

### Additional Server Info

I used ViaProxy, and I also created an [issue](https://github.com/ViaVersion/ViaProxy/issues/254) there, but they said to go here instead.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
- [X] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem

### PR DESCRIPTION
**Pull request by Beaness**
The use bed only supports players
Fixes https://github.com/ViaVersion/ViaRewind/issues/483
Fixes https://github.com/ViaVersion/ViaRewind/issues/447
Fixes https://github.com/ViaVersion/ViaRewind/issues/532

### CODE REVIEW

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_14to1_13_2/rewriter/EntityPacketRewriter1_14.java [hunk 1]
```diff
@@ -450,15 +450,18 @@ protected void registerRewrites() {
...
-                    PacketWrapper wrapper = PacketWrapper.create(ClientboundPackets1_13.PLAYER_SLEEP, null, event.user());
-                    wrapper.write(Types.VAR_INT, event.entityId());
-                    wrapper.write(Types.BLOCK_POSITION1_8, position);
-
-                    try {
-                        wrapper.scheduleSend(Protocol1_14To1_13_2.class);
-                    } catch (Exception ex) {
-                        ex.printStackTrace();
+                    // Only players can sleep in 1.13
+                    EntityType entityType = tracker(event.user()).entityType(event.entityId());
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_14to1_13_2/rewriter/EntityPacketRewriter1_14.java]: You can get the type from the event

File: common/src/main/java/com/viaversion/viabackwards/protocol/v1_14to1_13_2/rewriter/EntityPacketRewriter1_14.java [hunk 2]
```diff
@@ -450,15 +450,18 @@ protected void registerRewrites() {
...
+                    if (entityType == EntityTypes1_14.PLAYER) {
+                        PacketWrapper wrapper = PacketWrapper.create(ClientboundPackets1_13.PLAYER_SLEEP, null, event.user());
+                        wrapper.write(Types.VAR_INT, event.entityId());
+                        wrapper.write(Types.BLOCK_POSITION1_8, position);
+
+                        try {
+                            wrapper.scheduleSend(Protocol1_14To1_13_2.class);
+                        } catch (Exception ex) {
+                            ex.printStackTrace();
+                        }
```
Comment (kennytv) [inline common/src/main/java/com/viaversion/viabackwards/protocol/v1_14to1_13_2/rewriter/EntityPacketRewriter1_14.java]: Unrelated to the changes, but you can remove the try catch here

**Review by kennytv — APPROVED** [review]

**Comment by linsaftw** [comment]
Thank you !
